"""
Claude Code integration — hook into Claude Code's native hook
system so the daemon learns when an agent is `working`,
`awaiting-input`, or `idle` from the harness itself, not from
inferring it out of message text.

Claude Code's hook system (documented in the official docs)
lets you register shell scripts against lifecycle events. We
write one script that handles every event we care about, and
register it in `~/.claude/settings.json` against:

  - `PreToolUse`     → working      (tool call about to fire)
  - `Notification`   → awaiting-input  (permission prompt etc.)
  - `Stop`           → idle         (agent finished a turn)
  - `UserPromptSubmit` → working   (just got a new prompt)

The hook reads `$CLAUDE_AGENT_ID` (set by relaydeck when spawning
the harness) and POSTs to `${RELAYDECK_DAEMON_URL}/api/agents/<id>/state`
with the Bearer token from `~/.relaydeck/auth-token`.

## Install behavior

Idempotent. First run writes:
  - `~/.relaydeck/integrations/claude/relaydeck-state.sh`
    (the script — kept in our config home, not Claude's, so
    `relaydeck integration uninstall claude` can remove it cleanly
    without touching Claude's directory beyond removing one
    hook entry from settings.json)
  - merges the hook entries into `~/.claude/settings.json` if
    that file doesn't already reference our script

Second run is a no-op modulo updating the script contents in
case the operator pulled a newer relaydeck.

## Uninstall behavior

Removes the script file and strips the matching hook entries
from `settings.json`. Doesn't touch any other Claude hooks the
user might have configured.
"""

from __future__ import annotations

import json
import stat
from pathlib import Path
from typing import Literal

IntegrationState = Literal[
    "not-installed",
    "installed",
    "orphaned-registration",
    "orphaned-script",
    "outdated",
]


# Bumped whenever the rendered script body changes in a way that
# requires regenerating an already-installed hook. `_ensure_state_hook`
# (on spawn) re-renders when the on-disk script doesn't match, so
# operators upgrading from a broken build self-heal without a manual
# uninstall/reinstall. v2: read the event from stdin JSON, not $1.
_HOOK_VERSION = 2


# Event → semantic-status mapping. Defined once here so the
# script template stays in sync.
_EVENT_MAPPING = [
    ("PreToolUse", "working"),
    ("Notification", "awaiting-input"),
    ("Stop", "idle"),
    ("UserPromptSubmit", "working"),
]


_SCRIPT_TEMPLATE = """\
#!/usr/bin/env bash
# relaydeck integration hook for Claude Code.
# Auto-generated by `relaydeck integration install claude`.
# Do not edit — re-run the install command to regenerate.
# relaydeck-hook-version: __HOOK_VERSION__

set -eu

# Claude Code delivers the hook payload as JSON on stdin (it includes
# "hook_event_name"); it does NOT pass the event as a positional arg.
# Earlier relaydeck builds keyed off $1, which Claude never sets, so the
# case below always fell through to *) and status updates silently never
# fired. Read the event from stdin, falling back to $1 for arg-style
# callers (and the integration tests). The `! -t 0` guard avoids blocking
# on a controlling terminal when no payload is piped in.
PAYLOAD=""
if [ ! -t 0 ]; then
  PAYLOAD="$(cat || true)"
fi
EVENT="$(printf '%s' "$PAYLOAD" | sed -n 's/.*"hook_event_name"[[:space:]]*:[[:space:]]*"\\([A-Za-z]*\\)".*/\\1/p' | head -n1)"
if [ -z "$EVENT" ]; then
  EVENT="${1:-unknown}"
fi

STATUS=""
case "$EVENT" in
__EVENT_CASES__
  *) exit 0 ;;
esac

AGENT_ID="${CLAUDE_AGENT_ID:-${RELAYDECK_AGENT_ID:-}}"
if [ -z "$AGENT_ID" ]; then
  # No agent id in env — Claude Code was launched outside relaydeck.
  # Silently no-op so users running Claude directly aren't
  # broken by the hook's presence.
  exit 0
fi

DAEMON_URL="${RELAYDECK_DAEMON_URL:-http://127.0.0.1:8765}"
TOKEN=""
TOKEN_FILE="${HOME}/.relaydeck/auth-token"
if [ -n "${RELAYDECK_AUTH_TOKEN:-}" ]; then
  TOKEN="$RELAYDECK_AUTH_TOKEN"
elif [ -r "$TOKEN_FILE" ]; then
  TOKEN="$(cat "$TOKEN_FILE")"
fi

# Best-effort POST. We don't fail the hook on transport errors —
# the user's Claude session must not break because the daemon is
# down. `--max-time 2` keeps interactive prompts responsive.
curl -sS --max-time 2 \\
  -X POST \\
  -H "Content-Type: application/json" \\
  ${TOKEN:+-H "Authorization: Bearer ${TOKEN}"} \\
  -d "{\\"status\\": \\"${STATUS}\\", \\"source\\": \\"hook\\"}" \\
  "${DAEMON_URL}/api/agents/${AGENT_ID}/state" \\
  >/dev/null 2>&1 || true
"""


# Claude Code fires `Notification` for BOTH a genuine human-approval prompt
# ("Claude needs your permission to use Bash") AND the idle reminder ("Claude
# is waiting for your input"). relaydeck spawns claude with
# --dangerously-skip-permissions, so the approval case never occurs for our
# agents — a flat Notification→awaiting-input would leave every *finished*
# agent looking blocked-on-human (and, since awaiting-input outranks idle in
# the workspace-health roll-up, drag the whole workspace into a false alarm).
# So inspect the message: only a permission/approval wording sets
# awaiting-input; the idle reminder maps to idle. An empty message (the
# arg-style fallback / legacy callers with no JSON payload) preserves the prior
# awaiting-input mapping.
_NOTIFICATION_CASE = """\
  Notification)
    MSG="$(printf '%s' "$PAYLOAD" | sed -n 's/.*"message"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p' | head -n1)"
    case "$MSG" in
      "") STATUS="awaiting-input" ;;
      *permission*|*[Pp]ermission*|*approval*|*[Aa]pprove*) STATUS="awaiting-input" ;;
      *) STATUS="idle" ;;
    esac
    ;;"""


def _render_script() -> str:
    """Render the bash script with the event→status case
    statements interpolated from the mapping table."""
    cases = "\n".join(
        _NOTIFICATION_CASE
        if event == "Notification"
        else f'  {event}) STATUS="{status}" ;;'
        for event, status in _EVENT_MAPPING
    )
    return (
        _SCRIPT_TEMPLATE
        .replace("__EVENT_CASES__", cases)
        .replace("__HOOK_VERSION__", str(_HOOK_VERSION))
    )


def _script_path() -> Path:
    return Path.home() / ".relaydeck" / "integrations" / "claude" / "relaydeck-state.sh"


def _settings_path() -> Path:
    return Path.home() / ".claude" / "settings.json"


def _settings_references_script(target: str) -> bool:
    """True when ~/.claude/settings.json still wires any mapped event to TARGET."""
    sp = _settings_path()
    if not sp.exists():
        return False
    try:
        data = json.loads(sp.read_text())
    except (OSError, json.JSONDecodeError):
        return False
    hooks = data.get("hooks") or {}
    for ev, _ in _EVENT_MAPPING:
        for entry in hooks.get(ev) or []:
            if _entry_references(entry, target):
                return True
    return False


def _entry_references(entry: object, target: str) -> bool:
    # Claude Code's current schema: {"matcher": "...", "hooks": [{"type": "command", "command": "..."}]}.
    # Legacy flat shape from older relaydeck installs: {"matcher": "...", "command": "..."}.
    # Detect both so uninstall cleans up legacy entries written before the schema fix.
    if not isinstance(entry, dict):
        return False
    if entry.get("command") == target:
        return True
    for inner in entry.get("hooks") or []:
        if isinstance(inner, dict) and inner.get("command") == target:
            return True
    return False


class ClaudeIntegration:
    name = "claude"
    description = "Claude Code hooks: PreToolUse / Notification / Stop / UserPromptSubmit"
    kind = "hook"

    def script_is_current(self) -> bool:
        """True when the on-disk hook script matches what we'd render now.
        Lets `_ensure_state_hook` re-render an outdated script (e.g. a build
        that keyed the event off $1) on the next spawn without a manual
        uninstall/reinstall."""
        try:
            return _script_path().read_text() == _render_script()
        except OSError:
            return False

    def state(self) -> IntegrationState:
        """Report hook script + vendor registration alignment."""
        target = str(_script_path())
        script_exists = _script_path().is_file()
        registered = _settings_references_script(target)
        if not script_exists and not registered:
            return "not-installed"
        if not script_exists and registered:
            return "orphaned-registration"
        if script_exists and not registered:
            return "orphaned-script"
        if not self.script_is_current():
            return "outdated"
        return "installed"

    def is_installed(self) -> bool:
        return self.state() == "installed"

    def install(self) -> str:
        """Write the script + register the hook entries. Returns
        the script path (so the CLI can print it). Idempotent —
        existing entries pointing at our script are kept; missing
        events are added; the script body is always re-rendered."""
        script = _script_path()
        script.parent.mkdir(parents=True, exist_ok=True)
        script.write_text(_render_script())
        # Make the script executable. Claude Code spawns hooks
        # directly; without +x they'd fail with ENOEXEC.
        mode = script.stat().st_mode
        script.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

        sp = _settings_path()
        sp.parent.mkdir(parents=True, exist_ok=True)
        if sp.exists():
            try:
                data = json.loads(sp.read_text())
            except json.JSONDecodeError:
                data = {}
        else:
            data = {}
        hooks = data.setdefault("hooks", {})
        target = str(script)
        for ev, _ in _EVENT_MAPPING:
            entries = hooks.setdefault(ev, [])
            # Skip if already wired against our script — preserves
            # any other operator-owned hooks on the same event.
            if any(_entry_references(e, target) for e in entries):
                continue
            entries.append({
                "matcher": "*",
                "hooks": [{"type": "command", "command": target}],
            })
        sp.write_text(json.dumps(data, indent=2) + "\n")
        return str(script)

    def uninstall(self) -> bool:
        """Remove the script + strip our hook entries from
        settings.json. Other operator-owned hook entries on the
        same events are untouched. Returns True if anything was
        actually removed."""
        removed_any = False
        script = _script_path()
        if script.exists():
            try:
                script.unlink()
                removed_any = True
            except OSError:
                pass
        # Best-effort cleanup of the integration dir we created.
        try:
            script.parent.rmdir()
        except OSError:
            pass

        sp = _settings_path()
        if not sp.exists():
            return removed_any
        try:
            data = json.loads(sp.read_text())
        except json.JSONDecodeError:
            return removed_any
        hooks = data.get("hooks") or {}
        target = str(script)
        for ev in list(hooks.keys()):
            entries = hooks.get(ev) or []
            filtered = [e for e in entries if not _entry_references(e, target)]
            if len(filtered) != len(entries):
                removed_any = True
            if filtered:
                hooks[ev] = filtered
            else:
                hooks.pop(ev, None)
        if not hooks:
            data.pop("hooks", None)
        sp.write_text(json.dumps(data, indent=2) + "\n")
        return removed_any
